ld()
clean(destroy = TRUE)
source("packages.R")
source("functions.R")
plan <- drake_plan(dataset = prepare_dataset())
config <- make(plan)
o1 <- config$cache$get("prepare_dataset", namespace = "kernels")
config <- make(plan)
o2 <- config$cache$get("prepare_dataset", namespace = "kernels")
